### ISSUE TITLE
Extraction of Pose and Flow

### ISSUE THREAD

**Issue by kruthikakr** [AlbusPeter/P-CNN#1]
I am trying to run this , could you help me by providing the details of how to get the pose and flow data

**Comment by AlbusPeter** [comment]
Hi! As I mentioned in the Readme file, I extract the pose and flow features by using these two papers, "Realtime Multi-Person 2D Pose Estimation using Part Affinity Fields" and "FlowNet". You need the pre-trained models from those projects.

**Comment by kruthikakr** [comment]
Ya could you provide me the pose data of UCF101

**Comment by AlbusPeter** [comment]
Currently, I do not have the raw data. Sorry! You need to run it by yourself.
